language: node_js
node_js:
  - "12"

dist: trusty

branches:
  only:
    - master

script:
  - npm run lint
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true